name: Terraform Apply

on: workflow_dispatch

permissions:
  id-token: write # This is required for requesting the JWT   
  
env:
  OIDC_PROVIDER_NAME: ${{ vars.OIDC_PROVIDER_NAME }}
  JF_URL: https://${{ vars.JF_URL }}/
  JF_BUILD_NAME: 'web-goat-terraform'
  JF_BUILD_NUMBER: ${{ github.run_number }}  

jobs:
    crt-upd-repos:
        runs-on: ubuntu-latest

        steps:
        # Step 1: Check out the repository
        - name: Checkout repository
          uses: actions/checkout@v3

        # Step 2: Install Terraform CLI
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: 1.5.7 # Replace with your desired version

        # Step 3: Login to JFrog Terraform repository
            # Use the specific setup-cli branch
        - name: Setup JFrog CLI
          uses: jfrog/setup-jfrog-cli@v4
          id: setup-cli
          env:
            JF_URL: https://${{ vars.JF_URL }}/
          with:
            oidc-provider-name: ${{ env.OIDC_PROVIDER_NAME }}

        - name: Setup HCL credentials
          run: |
            mkdir -p ~/.terraform.d
            echo "{
            \"credentials\": {
            \"${{ vars.BE_FQDN }}\": {
              \"token\": \"${{ steps.setup-cli.outputs.oidc-token }}\"
            }}
              }" > ~/.terraform.d/credentials.tfrc.json

        # Step 4: Initialize Terraform
        - name: Terraform Init
          run: terraform init
            
        # Step 5: Apply Terraform
        - name: Terraform Apply
          run: terraform apply -auto-approve
          env:
            TF_VAR_JFROG_ACCESS_TOKEN_CI_INSTANCE: ${{ steps.setup-cli.outputs.oidc-token }}
            TF_VAR_JFROG_URL_CI_INSTANCE: ${{ vars.JFROG_URL_CI_INSTANCE }}
            TF_VAR_JFROG_ACCESS_TOKEN_CD_INSTANCE: ${{ steps.setup-cli.outputs.oidc-token }}
            TF_VAR_JFROG_URL_CD_INSTANCE: ${{ vars.JFROG_URL_CD_INSTANCE }}
            TF_VAR_JFROG_ACCESS_TOKEN_EDGE: ${{ steps.setup-cli.outputs.oidc-token }}
            TF_VAR_JFROG_URL_EDGE: ${{ vars.JFROG_URL_EDGE }}
            TF_API_TOKEN: ${{ steps.setup-cli.outputs.oidc-token }}
            TF_VAR_BE_FQDN: ${{ vars.BE_FQDN }}
            TF_VAR_REPO_LIST_FILE: ${{ vars.REPO_LIST_FILE }}
            OIDC_PROVIDER_NAME: ${{ vars.OIDC_PROVIDER_NAME }}

        - name: JFrog Build
          run: |
            jf rt build-add-dependencies .           
            jf rt build-add-git 
            jf rt build-collect-env 
            jf rt build-add-dependencies --from-rt tf-repo-manager-module/jfrog/soleng/demorepos/v1.0.zip
            jf rt build-publish
            